# Generated by Django 3.0a1 on 2019-09-19 22:28

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('text', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='text')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 9, 19, 22, 28, 18, 707251, tzinfo=utc), verbose_name='date')),
            ],
        ),
    ]
