# Generated by Django 3.0a1 on 2019-09-26 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inote', '0002_auto_20190923_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inote',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 26, 1, 23, 4, 3392, tzinfo=utc), verbose_name='date'),
        ),
    ]
